name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: test
        run: |
          echo pwd
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        run: |
          pelican content -s pelicanconf.py

      - name: Push site
        uses: ad-m/github-push-action@v0.6.0
        github_token: %{{secrets.TOKEN}}
        repository: bedlamzd.github.io
