name: Site publishing

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout internals
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          path: internals

      - name: Checkout site
        uses: actions/checkout@v2
        with:
          repository: bedlamzd/bedlamzd.github.io
          persist-credentials: false
          fetch-depth: 0
          path: bedsite

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: ./internals
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        working-directory: ./internals
        run: |
          pelican content -o ../bedsite/ -s pelicanconf.py

      - name: Commit changes
        working-directory: ./bedsite
        run: |
          git config --local user.email "bedlamzd@gmail.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "Internal changes" -a

      - name: Push site
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.TOKEN}}
          repository: bedlamzd/bedlamzd.github.io
          directory: ./bedsite
