name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout internals
        uses: actions/checkout@v2
        with:
          path: internals

      - name: Checkout site
        uses: actions/checkout@v2
        with:
          path: bedsite

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: ./internals
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        working-directory: ./internals
        run: |
          pelican content -o ../bedsite/ -s pelicanconf.py

      - name: Git test
        working-directory: ../bedsite
        run: |
          git status

      - name: Push site
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.TOKEN}}
          repository: bedlamzd.github.io
          directory: ../bedsite/
